### PR TITLE
add more info to readme

### PR DESCRIPTION
**Pull request by flipflopsimsommer**
i thought that might be usefull information

### CODE REVIEW

**Comment by evanlucas** [comment]
I like adding the comment about the config being saved. I do think the forever section should be more of a wiki page or something though. Possibly even adding additional options?

**Comment by flipflopsimsommer** [comment]
in the meantime i personally use [pm2](https://www.npmjs.com/package/pm2) instead of forever, it even starts after reboots and has better monitoring options.
should i make a pull request containing only the configuration part?
you should consider linking the wiki though.

**Comment by evanlucas** [comment]
Yea, that would be great. Feel free to add a wiki page with it if you want. :]

**Comment by flipflopsimsommer** [comment]
part one is done. i wrote a wiki about pm2 already i will adjust it for gcr next week

**Comment by evanlucas** [comment]
Thanks! Landed in 53ef873c6bd18ef0b6c195d0ed200702fd8ebc49 with a slightly modified commit message

**Comment by flipflopsimsommer** [comment]
just added the wiki, hope you like it - if so you might consider link it from the __readme.md__

btw you might update your npm modules, i tested it (in my envirument) with the latest versions, it works fine. but mybe there are cases where they woudn't work?

**Comment by evanlucas** [comment]
Awesome. That sounds great. Would definitely be open to a PR for adding it to the readme if you're interested. I also have plans to add a test suite as it is desperately needed. Just haven't had the time yet. :]

**Comment by flipflopsimsommer** [comment]
you already saved my time by writing the core, tell me where i can help, i can at least try... ;)

**Pull request closed without merging**
